import { readFileSync, writeFileSync } from 'node:fs';

const version = readFileSync(new URL('../VERSION', import.meta.url), 'utf8').trim();
if (!/^\d+\.\d+\.\d+(?:-[0-9A-Za-z.-]+)?(?:\+[0-9A-Za-z.-]+)?$/.test(version)) {
  throw new Error('VERSION must contain a version such as 0.2.0 or 0.3.0-beta.1.');
}

const page = new URL('../web/index.html', import.meta.url);
const html = readFileSync(page, 'utf8');
const marker = /(<span class="version">)[^<]*(<\/span>)/;
if (!marker.test(html)) throw new Error('Viewer version element is missing.');
const updated = html.replace(marker, `$1/ ${version}$2`);
if (updated !== html) writeFileSync(page, updated);

// VERSION is the release source. Build fingerprints identify dirty/local builds
// without claiming that the previous Git commit contains uncommitted changes.
const {createHash}=await import('node:crypto');
const {readdirSync}=await import('node:fs');
const {execFileSync}=await import('node:child_process');
const hash=value=>createHash('sha256').update(value).digest('hex');
const packagePath=new URL('../package.json',import.meta.url);
const pkg=JSON.parse(readFileSync(packagePath,'utf8'));
if(pkg.version!==version){pkg.version=version;writeFileSync(packagePath,JSON.stringify(pkg,null,2)+'\n');}
const src=new URL('../src/',import.meta.url);
const files=readdirSync(src).filter(f=>f.endsWith('.ts')&&f!=='build-info.ts').sort();
const buildHash=hash(files.map(f=>f+'\n'+readFileSync(new URL(f,src),'utf8')).join('\n'));
let revision=null;
try {revision=execFileSync('git',['rev-parse','HEAD'],{encoding:'utf8',stdio:['ignore','pipe','ignore']}).trim();}catch {/* Installed archives have no Git checkout. */}
const skill=hash(readFileSync(new URL('../skills/session-analysis/SKILL.md',import.meta.url)));
const guide=hash(readFileSync(new URL('../skills/session-analysis/references/interpretation.md',import.meta.url)));
writeFileSync(new URL('build-info.ts',src),`// Generated by build-version.mjs.\nexport const BUILD=${JSON.stringify({version,revision,build_sha256:buildHash,skill_sha256:skill,guide_sha256:guide})} as const;\n`);
